### ISSUE TITLE
All automation features and blocks from Quark are disabled

### ISSUE THREAD

**Issue by mpavkovic** [AllTheMods/atm6-sky#377]
**All automation features and blocks from Quark are disabled**
I wanted to craft an Obsidian Pressure Plate from Quark, but there was no recipe for it in JEI. By checking the quark-common.toml I've found out that all of the automation features are disabled.

```toml
[categories]
	Automation = false
	Building = true
	Client = true
	Experimental = false
	Management = true
	Mobs = true
	Oddities = false
	Tools = false
	Tweaks = true
	World = false

[automation]
	"Chain Linkage" = false
	"Chains Connect Blocks" = false
	Chute = false
	"Color Slime" = false
	"Dispensers Place Blocks" = false
	"Ender Watcher" = false
	"Endermites Form Shulkers" = false
	"Feeding Trough" = false
	Gravisand = false
	"Iron Rod" = false
	"Metal Buttons" = false
	"Obsidian Plate" = false
	"Pistons Move Tile Entities" = false
	"Redstone Circuit" = false
	"Weather Sensor" = false
```

**To Reproduce**
1. Open JEI, search Obsidian Pressure Plate
2. Click to see the recipe
3. The recipe is missing

**Expected behavior**
I'm not sure if this is intended or not? Anyway, Obsidian Pressure Plate is really useful block as it only detects players and it would be nice to have it in game.
